sudo: required

language: java

services:
  - docker

jdk:
  - oraclejdk8


# Using default 'test' stage for our tests, and only running deploy stage
# (after merge) on master branch
stages:
  - site_documentation
  - release

# To prevent Travis from also running build on pushed tags
# (and have endless loop of builds for every git push --tags)
branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]+$/

# Prepare site documentation
before_deploy:
  - echo $TRAVIS_BUILD_STAGE_NAME
  - if [[ $TRAVIS_BUILD_STAGE_NAME = Site_documentation ]]; then rm -rf docs && mvn site -B; fi
  - if [[ $TRAVIS_BUILD_STAGE_NAME = ReleaseToGithub ]]; then ./prepare_release.sh; fi
  - echo "before deploy"


# Last step in build checks if we should release or not
after_deploy:
  - if [[ $TRAVIS_BRANCH == "test-release-notes" ]] && [[ $TRAVIS_PULL_REQUEST == "false" ]]; then ./prepare_release.sh; fi


# List of jobs to run, tied to specific stages
jobs:
  include:
    - stage: test
      name: test
      install: skip
      script:
        - echo "testing"
    - stage: site_documentation
      name: site_documentation
      install: skip
      script: skip
      deploy:
        - provider: pages   # how to have multiple deploy jobs
          name: update_gh_pages
          skip_cleanup: true
          github-token: $GREN_GITHUB_TOKEN
          local_dir: docs/
          env: SITE=true
          on:
            branch: test-release-notes
    - stage: release
      name: releaseToGitHub
      install: skip
      script: skip          # skip default tests
      deploy:
        - provider: releases
          name: $GIT_TAG
          tag_name: $GIT_TAG
          api_key: $GREN_GITHUB_TOKEN
          skip_cleanup: true
          on:
            all_branches: true
