sudo: required

language: java

services:
  - docker

jdk:
  - oraclejdk8


# Using default 'test' stage for our tests, and only running deploy stage
# (after merge) on master branch
stages:
  - test
  - name: site_documentation
    if: branch = test-release-notes
  - name: release
    if: branch = test-release-notes

# To prevent Travis from also running build on pushed tags
# (and have endless loop of builds for every git push --tags)
branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]+$/


# Check which deploy provider. Before site documentation deployment we need to generate the pages
# Before release we need to confirm the git tag is correct and prepare release notes
# export the git tag pointing to the current commit - must be done here to be accessible for release job
before_deploy:
  - echo $TRAVIS_JOB_NAME
  - if [[ $TRAVIS_JOB_NAME = site_documentation ]]; then rm -rf docs && mvn site -B; fi
  - |
    if [[ $TRAVIS_JOB_NAME = release ]]; then
      git fetch --tags -q
      export GIT_TAG=$(git describe --tags $TRAVIS_COMMIT)
      ./prepare_release.sh $GIT_TAG;
    fi


# List of jobs to run, tied to specific stages
jobs:
  include:
    - stage: test
      name: test
      install: skip
      script:
        - echo "testing"
    - stage: site_documentation
      name: site_documentation
      install: skip
      script: skip
      deploy:
        provider: pages
        skip_cleanup: true
        github-token: $GREN_GITHUB_TOKEN
        local_dir: docs/
        on:
          branch: test-release-notes
    - stage: release
      name: release
      install: skip
      script: skip          # skip default tests
      deploy:
        provider: releases
        name: $GIT_TAG
        tag_name: $GIT_TAG
        api_key: $GREN_GITHUB_TOKEN
        skip_cleanup: true
        on:
          all_branches: true