sudo: required

language: java

services:
  - docker

jdk:
  - oraclejdk8


# Using default 'test' stage for our tests, and only running deploy stage
# (after merge) on master branch
stages:
  - name: release
    if: branch = test-release-notes AND type != pull_request

# To prevent Travis from also running build on pushed tags
# (and have endless loop of builds for every git push --tags)
branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]+$/

before_deploy:
  - git fetch --tags -q
  - export GIT_TAG=$(git describe --tags $TRAVIS_COMMIT)    # export the git tag pointing to the current commit
  - echo $GIT_TAG
  - export REGEX=^[0-9]+\.[0-9]+\.[0-9]+$
  - if [[ ! $GIT_TAG =~ $REGEX ]]; then echo "Nope"; fi
  - npm install github-release-notes -g
  - gren release --debug --tags=$GIT_TAG --data-source=commits -T $GREN_GITHUB_TOKEN;
  - mvn versions:set -DnewVersion=$GIT_TAG -DgenerateBackupPoms=false   # Step version in pom file
  - git status
  - git diff pom.xml

after_deploy:
  - if [[ $TRAVIS_BRANCH == "test-release-notes" ]] && [[ $TRAVIS_PULL_REQUEST == "false" ]]; then echo "will deploy"; else echo "will not deploy"; fi


# List of jobs to run, tied to specific stages
jobs:
  include:
    - stage: release
      name: releaseToGitHub
      install: skip
      script: skip          # skip default tests
      deploy:
        provider: releases
        name: $GIT_TAG
        tag_name: $GIT_TAG
        api_key: $GREN_GITHUB_TOKEN
        skip_cleanup: true
        on:
          all_branches: true
