sudo: required

language: java

services:
  - docker

jdk:
  - oraclejdk8

env:
  - global:
    - SHOULD_RELEASE=false

# Using default 'test' stage for our tests, and only running deploy stage
# (after merge) on master branch
stages:
  - prepare_release
  - release

# To prevent Travis from also running build on pushed tags
# (and have endless loop of builds for every git push --tags)
branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]+$/


after_deploy:
  - if [[ $TRAVIS_BRANCH == "test-release-notes" ]] && [[ $TRAVIS_PULL_REQUEST == "false" ]]; then echo "will deploy"; else echo "will not deploy"; fi


# List of jobs to run, tied to specific stages
jobs:
  include:
    - stage: prepare_release
      name: prepare_release
      install: skip
      script:
        - git fetch --tags -q
        - export GIT_TAG=$(git describe --tags $TRAVIS_COMMIT)  # export the git tag pointing to the current commit
        - echo $GIT_TAG $SHOULD_RELEASE
        - ./prepare_release.sh $GIT_TAG $SHOULD_RELEASE
    - stage: release
      name: releaseToGitHub
      install: skip
      script: skip          # skip default tests
      deploy:
        provider: releases
        name: $GIT_TAG
        tag_name: $GIT_TAG
        api_key: $GREN_GITHUB_TOKEN
        skip_cleanup: true
        on:
          all_branches: true
          condition: $SHOULD_RELEASE = true